mapa_provincias = {
    'STA. CRUZ DE TENERIFE': 'Santa Cruz De Tenerife',
    'SANTA CRUZ DE TENERIFE': 'Santa Cruz De Tenerife',
    'ILLES BALEARS': 'Illes Balears',
    'BALEARES': 'Illes Balears',
    'A CORUÑA': 'A Coruña',
    'GIRONA': 'Girona',
    'LAS PALMAS': 'Las Palmas',
    'PONTEVEDRA': 'Pontevedra',
    'CANTABRIA': 'Cantabria',
    'MALAGA': 'Málaga',
    'ALMERIA': 'Almería',
    'MURCIA': 'Murcia',
    'ALBACETE': 'Albacete',
    'AVILA': 'Ávila',
    'ARABA/ALAVA': 'Araba/Álava',
    'BADAJOZ': 'Badajoz',
    'ALICANTE': 'Alacant/Alicante',
    'CASTELLON': 'Castelló/Castellón',
    'OURENSE': 'Ourense',
    'BARCELONA': 'Barcelona',
    'BURGOS': 'Burgos',
    'CACERES': 'Cáceres',
    'CADIZ': 'Cádiz',
    'CIUDAD REAL': 'Ciudad Real',
    'JAEN': 'Jaén',
    'CORDOBA': 'Córdoba',
    'CUENCA': 'Cuenca',
    'GRANADA': 'Granada',
    'GUADALAJARA': 'Guadalajara',
    'GIPUZKOA': 'Gipuzkoa/Guipúzcoa',
    'HUESCA': 'Huesca',
    'LEON': 'León',
    'LLEIDA': 'Lleida',
    'LA RIOJA': 'La Rioja',
    'SORIA': 'Soria',
    'NAVARRA': 'Navarra',
    'CEUTA': 'Ceuta',
    'LUGO': 'Lugo',
    'MADRID': 'Madrid',
    'PALENCIA': 'Palencia',
    'SALAMANCA': 'Salamanca',
    'SEGOVIA': 'Segovia',
    'SEVILLA': 'Sevilla',
    'TOLEDO': 'Toledo',
    'TARRAGONA': 'Tarragona',
    'TERUEL': 'Teruel',
    'VALENCIA': 'València/Valencia',
    'VALLADOLID': 'Valladolid',
    'BIZKAIA': 'Bizkaia/Vizcaya',
    'ZAMORA': 'Zamora',
    'ZARAGOZA': 'Zaragoza',
    'MELILLA': 'Melilla',
    'ASTURIAS': 'Asturias',
    'HUELVA': 'Huelva'
}