mapa_provincias = {
    'STA. CRUZ DE TENERIFE': 'Santa Cruz De Tenerife',
    'SANTA CRUZ DE TENERIFE': 'Santa Cruz De Tenerife',
    'ILLES BALEARS': 'Illes Balears',
    'BALEARES': 'Illes Balears',
    'A CORUÑA': 'A Coruña',
    'GIRONA': 'Girona',
    'LAS PALMAS': 'Las Palmas',
    'PONTEVEDRA': 'Pontevedra',
    'CANTABRIA': 'Cantabria',
    'MALAGA': 'Málaga',
    'ALMERIA': 'Almería',
    'MURCIA': 'Murcia',
    'ALBACETE': 'Albacete',
    'AVILA': 'Ávila',
    'ARABA/ALAVA': 'Araba/Álava',
    'BADAJOZ': 'Badajoz',
    'ALICANTE': 'Alacant/Alicante',
    'CASTELLON': 'Castelló/Castellón',
    'OURENSE': 'Ourense',
    'BARCELONA': 'Barcelona',
    'BURGOS': 'Burgos',
    'CACERES': 'Cáceres',
    'CADIZ': 'Cádiz',
    'CIUDAD REAL': 'Ciudad Real',
    'JAEN': 'Jaén',
    'CORDOBA': 'Córdoba',
    'CUENCA': 'Cuenca',
    'GRANADA': 'Granada',
    'GUADALAJARA': 'Guadalajara',
    'GIPUZKOA': 'Gipuzkoa/Guipúzcoa',
    'HUESCA': 'Huesca',
    'LEON': 'León',
    'LLEIDA': 'Lleida',
    'LA RIOJA': 'La Rioja',
    'SORIA': 'Soria',
    'NAVARRA': 'Navarra',
    'CEUTA': 'Ceuta',
    'LUGO': 'Lugo',
    'MADRID': 'Madrid',
    'PALENCIA': 'Palencia',
    'SALAMANCA': 'Salamanca',
    'SEGOVIA': 'Segovia',
    'SEVILLA': 'Sevilla',
    'TOLEDO': 'Toledo',
    'TARRAGONA': 'Tarragona',
    'TERUEL': 'Teruel',
    'VALENCIA': 'València/Valencia',
    'VALLADOLID': 'Valladolid',
    'BIZKAIA': 'Bizkaia/Vizcaya',
    'ZAMORA': 'Zamora',
    'ZARAGOZA': 'Zaragoza',
    'MELILLA': 'Melilla',
    'ASTURIAS': 'Asturias',
    'HUELVA': 'Huelva'
}

# Kept for potential future use (not used in current schema)
mapa_codigo_provincias = {
    'Araba/Álava': 1,
    'Albacete': 2,
    'Alacant/Alicante': 3,
    'Almería': 4,
    'Ávila': 5,
    'Badajoz': 6,
    'Illes Balears': 7,
    'Barcelona': 8,
    'Burgos': 9,
    'Cáceres': 10,
    'Cádiz': 11,
    'Castelló/Castellón': 12,
    'Ciudad Real': 13,
    'Córdoba': 14,
    'A Coruña': 15,
    'Cuenca': 16,
    'Girona': 17,
    'Granada': 18,
    'Guadalajara': 19,
    'Gipuzkoa/Guipúzcoa': 20,
    'Huelva': 21,
    'Huesca': 22,
    'Jaén': 23,
    'León': 24,
    'Lleida': 25,
    'La Rioja': 26,
    'Lugo': 27,
    'Madrid': 28,
    'Málaga': 29,
    'Murcia': 30,
    'Navarra': 31,
    'Ourense': 32,
    'Asturias': 33,
    'Palencia': 34,
    'Las Palmas': 35,
    'Pontevedra': 36,
    'Salamanca': 37,
    'Santa Cruz De Tenerife': 38,
    'Cantabria': 39,
    'Segovia': 40,
    'Sevilla': 41,
    'Soria': 42,
    'Tarragona': 43,
    'Teruel': 44,
    'Toledo': 45,
    'València/Valencia': 46,
    'Valladolid': 47,
    'Bizkaia/Vizcaya': 48,
    'Zamora': 49,
    'Zaragoza': 50,
    'Ceuta': 51,
    'Melilla': 52
}

mapa_codigo_ccaa = {
    '01': 'Andalucía',
    '02': 'Aragón',
    '03': 'Illes Balears',
    '04': 'Canarias',
    '05': 'Cantabria',
    '06': 'Castilla - La Mancha',
    '07': 'Castilla y León',
    '08': 'Cataluña',
    '09': 'Ceuta',
    '10': 'Extremadura',
    '11': 'Galicia',
    '12': 'La Rioja',
    '13': 'Madrid, Comunidad de',
    '14': 'Melilla',
    '15': 'Murcia, Región de',
    '16': 'Navarra, Comunidad Foral de',
    '17': 'País Vasco',
    '18': 'Principado de Asturias',
    '19': 'Comunitat Valenciana'
}

mapa_provincia_a_ccaa = {
    'Araba/Álava': '17',
    'Albacete': '06',
    'Alacant/Alicante': '19',
    'Almería': '01',
    'Ávila': '07',
    'Badajoz': '10',
    'Illes Balears': '03',
    'Barcelona': '08',
    'Burgos': '07',
    'Cáceres': '10',
    'Cádiz': '01',
    'Castelló/Castellón': '19',
    'Ciudad Real': '06',
    'Córdoba': '01',
    'A Coruña': '11',
    'Cuenca': '06',
    'Girona': '08',
    'Granada': '01',
    'Guadalajara': '06',
    'Gipuzkoa/Guipúzcoa': '17',
    'Huelva': '01',
    'Huesca': '02',
    'Jaén': '01',
    'León': '07',
    'Lleida': '08',
    'La Rioja': '12',
    'Lugo': '11',
    'Madrid': '13',
    'Málaga': '01',
    'Murcia': '15',
    'Navarra': '16',
    'Ourense': '11',
    'Asturias': '18',
    'Palencia': '07',
    'Las Palmas': '04',
    'Pontevedra': '11',
    'Salamanca': '07',
    'Santa Cruz De Tenerife': '04',
    'Cantabria': '05',
    'Segovia': '07',
    'Sevilla': '01',
    'Soria': '07',
    'Tarragona': '08',
    'Teruel': '02',
    'Toledo': '06',
    'València/Valencia': '19',
    'Valladolid': '07',
    'Bizkaia/Vizcaya': '17',
    'Zamora': '07',
    'Zaragoza': '02',
    'Ceuta': '09',
    'Melilla': '14'
}

def get_provincia_mappings(provincia):
    normalized = mapa_provincias.get(provincia, provincia)
    codigo_provincia = mapa_codigo_provincias.get(normalized)
    codigo_ca = mapa_provincia_a_ccaa.get(normalized)
    return normalized, codigo_provincia, codigo_ca