name: Actualizar datos diarios

on:
  schedule:
    - cron: '0 6 * * *'  # a las 6 AM UTC
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Activar entorno virtual
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: Instalar dependencias
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar extracción diaria
        run: |
          jupyter nbconvert --to script notebooks/02_Extraccion_Diaria.ipynb
          python notebooks/02_Extraccion_Diaria.py





